config/routes.rb
# NOTE: (cmhobbs) if ArgumentError exceptions arise during boot or on
#      loading routes, first assume clashes with a resources block as
#      noted in the rails 3.2->4.0 upgrade document:
#
#      https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#action-pack
Serve2perform::Application.routes.draw do
  resources :mentorship_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'mentorship_circles/join',  to: 'mentorship_circles#join'
  post 'mentorship_circles/leave', to: 'mentorship_circles#leave'

  resources :collaboration_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'collaboration_circles/join',  to: 'collaboration_circles#join'
  post 'collaboration_circles/leave', to: 'collaboration_circles#leave'

  mount Serve2perform::API => '/'

  resources :inquiries do
    resources :comments
    member do
      get 'documents'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :user_groups do
    collection do
      get ':id/approve' => 'user_groups#approve'
      get 'register'
      get 'manage'
      put 'destroy_many'
      post 'destroy_many'
    end
  end

  resources :coach_action_plans

  resources :mentor_action_plans

  resources :volunteer_action_plans

  resources :comments

  resources :recognitions do
    collection do
      get 'find'
    end
  end

  resources :feedbacks

  resources :facilities do
    collection do
      get 'new'
      get 'show'
      post 'edit'
    end
  end

  resources :testimonials do
    collection do
      get ':id/approve' => 'testimonials#approve'
    end
  end

  resources :fast_contents do
    member do
      get 'documents'
      get 'audio'
    end
  end

  resources :user_licenses do
    collection do
      get 'manage'
      put 'update_many'
    end
  end

  resources :videos

  resources :pacs do
    resources :comments
    collection do
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'cancel'
    end
  end

  resources :pac_members do
    collection do
      get ':id/approve' => 'pac_members#approve'
      get 'register'
      post :invite
    end
  end

  resources :best_practices do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :recommendations do
    resources :comments
    collection do
      get 'find'
      get 'list'
      get ':id/approve' => 'recommendations#approve'
      get 'register_pde'
    end
    member do
      post 'validate', to: 'socializations#validate'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  resources :users do
    collection do
      get 'find'
      get 'historical_opportunities'
      get 'chatter'
      get 'manage'
      put 'update_many'
    end
    member do
      get 'avatars'
    end
  end

  devise_scope :users do
    get '/users/historical_opportunities' => 'users#historical_opportunities'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'

    # FIXME: (cmhobbs) changing this "match" to "get" breaks hard:
    #       Invalid route name, already in use: 'user'
    #
    #       userdefs at line 152 may be messing with it and i'm not
    #       sure if this line is needed anymore?
    # match '/users/:id' => 'users#show', :as => :user
  end

  resources :opportunities do
    collection do
      get :autocomplete_opportunity_title
      post 'update_many'
      get 'edit_many'
      get 'getFacilities'
      get 'getAddress'
      get 'getPrice'
      get 'register_pde'
      get 'getType'
      get 'oneClickRegister'
      get 'oneClickWebRegister'
    end
  end

  resources :competencies, only: [:update]

  resources :assessments

  resources :assessment_reports do
    member do
      get :share
      post :share_with_email
    end
  end

  resources :organizations, param: :slug, only: %i[new create show edit update] do
    member do
      get :sync
      get :sync_linkedin
      get 'findUsers' => 'organizations#find_users'
      get 'analytics' => 'organizations#analytics'
      get 'avatars'
      get 'banners'
      get 'search'
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'resources'
      post 'add_users'
    end
  end

  post 'organizations/leave', to: 'organizations#leave'

  resources :invites do
    collection do
      get :invite_email
      post :send_email
    end
  end

  resources :coupon_uses, only: %i[new create]

  resources :assessment_purchases, only: %i[show new create]

  resources :user_license_purchases, only: %i[show new create]

  resources :single_user_license_purchases, only: %i[show new create]

  resources :opportunity_applications

  resources :opportunity_scholarships, only: %i[new create]

  resources :opportunity_purchases

  resources :recommendation_applications

  resources :support_requests, only: %i[new create]

  resources :skills do
    collection do
      post 'update_many'
      get 'edit_many'
    end
  end

  resources :organization_reports do
    member do
      get  :share
      post :share_with_email
    end
  end

  resources :admin do
    collection do
      get 'reports'
      get 'scholarship_request'
    end
  end

  resources :availability do
    collection do
      post 'edit'
    end
  end

  resources :pac_availability do
    collection do
      post 'edit'
    end
  end

  resources :canvas do
    collection do
      get 'canvas' => 'canvas#index'
      post 'canvas' => 'canvas#post'
      get 'callback' => 'static#callback'
    end
  end

  devise_scope :user do
    # root to: 'home#index'
    root to: 'devise/sessions#new'
  end

  get '/signup' => 'signup#index'

  get '/resources' => 'pages#resources'
  get '/ondemand' => 'pages#on_demand'
  get '/collisions' => 'pages#collisions'
  get '/certifications' => 'pages#certifications'
  get '/about' => 'pages#about'
  get '/speakerseries' => 'pages#speaker_series'
  get '/list' => 'pages#list'
  get '/thoughtleadership' => 'pages#thought_leadership'
  get '/templates' => 'pages#templates'
  get '/marketplace' => 'home#index'

  require 'sidekiq/web'
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'sidekiqadmin' && password == 'S2Pworkers!'
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  require 'resque/server'
  Resque::Server.use(Rack::Auth::Basic) do |username, password|
    username == 'resqueadmin' && password == 'S2Pworkers!'
  end
  mount Resque::Server.new, at: '/resque'

  get '/marketplace/', to: 'marketplace#index'

  post 'accounts/generate', to: 'accounts#generate'
end

app/controllers/best_practices_controller.rb
# frozen_string_literal: true

class BestPracticesController < ApplicationController
  before_filter :authenticate_user!

  expose(:all_groups_sorted) do
    current_user.unique_groups.sort_by(&:title)
  end

  def index
    if best_practices_params[:organization_id].present?
      unless best_practices_params[:organization_id] == ['']
        @organization = best_practices_params[:organization_id]
      end
    else
      @organization = current_user.unique_groups
    end

    @best_practices = BestPractice.where(organization_id: @organization)

    respond_to do |format|
      format.html
      format.json { render json: @best_practices }
    end
  end

  def show
    @best_practice = BestPractice.find(best_practices_params[:id])
    @commentable   = @best_practice
    @comments      = @commentable.comments
    @comment       = Comment.new
    @organization  = current_user.organization

    respond_to do |format|
      format.html
      format.json { render json: @best_practice }
    end
  end

  def new
    if best_practices_params[:organization_id].present?
      unless best_practices_params[:organization_id] == ['']
        @organization_id = best_practices_params[:organization_id]
      end
    else
      @organization_id = nil
    end

    @best_practice = BestPractice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @best_practice }
    end
  end

  def edit
    @best_practice = BestPractice.find(best_practices_params[:id])
  end

  # FIXME: (cmhobbs+tyreldenison) refactor this.  severl methods could be extracted
  def create
    best_practices_params[:best_practice][:organization_id].each do |organization_id|
      @best_practice                 = BestPractice.new
      @best_practice.organization_id = organization_id
      @best_practice.title           = params[:best_practice][:title]
      @best_practice.body            = params[:best_practice][:body]
      @best_practice.anonymous       = params[:best_practice][:anonymous]
      @best_practice.emb_link        = params[:best_practice][:emb_link]
      @best_practice.ext_link        = params[:best_practice][:ext_link]
      @best_practice.documents       = params[:best_practice][:documents]
      @best_practice.documents_cache = params[:best_practice][:documents_cache]
      @best_practice.audio_cache     = params[:best_practice][:audio_cache]

      if !params[:best_practice][:ext_link].empty? && params[:best_practice][:link_title].empty?
        @best_practice.link_title = params[:best_practice][:ext_link]
      else
        @best_practice.link_title = params[:best_practice][:link_title]
      end

      @best_practice.user_id         = current_user.id
      @category                      = @best_practice.category

      # XXX (cmhobbs) GOTCHA, @best_practice will repeatedly get clobbered
      if @best_practice.save
        if current_user.provider == 'salesforce'
          @client = Databasedotcom::Client.new('./config/databasedotcom.yml')
          @client.authenticate token: current_user.access_key, instance_url: current_user.instance_url
          @client.version = '23.0'
          @me = Databasedotcom::Chatter::User.find(@client, 'me')
          @me.post_status("I just added an idea about #{@best_practice.title} on serve2perform. ##{@best_practice.category.gsub(/\s+/, '').downcase}")
        # FIXME: (cmhobbs) extract this into some kind of notifier
        elsif @best_practice.organization_id?
          if @best_practice.organization.members.empty?
            BestPracticeEmailWorker.perform_async(@best_practice.id, @best_practice.organization.users.pluck(:id))
          else
            @best_practice.organization.members.each do |member|
              next if member.mute_notifications

              # NOTE (cmhobbs) rails 4.2 change:
              Notifier.delay.new_best_practice_email(member, @best_practice)
              # Notifier.new_best_practice_email(member, @best_practice).deliver_later
            end

            # NOTE (conradwt) Is the following line required?
            # BestPracticeEmailWorker.perform_async(@best_practice.id, @best_practice.organization.members.pluck(:id))
          end
        else
          BestPracticeEmailWorker.perform_async(@best_practice.id, @best_practice.user.organization.users.pluck(:id))
        end
      end

      if @best_practice.save && @best_practice.is_public
        EmailWorker.perform_async(@best_practice.id)
      end
    end

    # NOTE (cmhobbs) will redirect to the last created best practice
    respond_to do |format|
      format.html { redirect_to @best_practice, notice: 'Your Insight was successfully created.' }
      format.json { render json: @best_practice, status: :created, location: @best_practice }
    end
  end

  def update
    @best_practice = BestPractice.find(best_practices_params[:id])

    respond_to do |format|
      if @best_practice.update_attributes(best_practices_params[:best_practice])
        format.html { redirect_to @best_practice, notice: 'Insight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @best_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  def documents
    Rails.logger.warn('Tombstone 8-3-2015 MK: Deprecate this method BestPractices#documents')
    best_practice = BestPractice.find(best_practices_params[:id])
    send_file best_practice.documents.path
  end

  def audio
    Rails.logger.warn('Tombstone 8-3-2015 MK: Deprecate this method BestPractices#audio')
    best_practice = BestPractice.find(best_practices_params[:id])
    send_file best_practice.audio.path
  end

  def destroy
    @best_practice = BestPractice.find_by(id: params[:id])

    if @best_practice&.destroy
      redirect_to best_practices_path
      # respond_to do |format|
      #   redirect_to best_practices_path
      #   #format.html { redirect_to organization_path(current_user.organization), notice: "Insight was sucessfully deleted." }
      #   format.json { head :no_content }
      # end
    end
  end

  def duplicate
    @organization      = current_user.organization
    @best_practice_dup = BestPractice.find(best_practices_params[:id])
    @new_best_practice = @best_practice_dup.dup

    @new_best_practice.category = BestPracticeCategory.find(best_practices_params[:organization][:best_practice_category_id]).title
    @new_best_practice.best_practice_category_id = best_practices_params[:organization][:best_practice_category_id]
    @new_best_practice.is_public = false
    @new_best_practice.documents = @best_practice_dup.documents
    @new_best_practice.documents_cache = @best_practice_dup.documents_cache
    @new_best_practice.audio = @best_practice_dup.audio
    @new_best_practice.audio_cache = @best_practice_dup.audio_cache
    @new_best_practice.comments = @best_practice_dup.comments.map(&:dup)

    @best_practice_dup.likers(User).each do |liker|
      liker.like!(@new_best_practice)
    end

    respond_to do |format|
      if @new_best_practice.save!
        format.html { redirect_to @new_best_practice, notice: "Insight was successfully added to your internal page under category #{@new_best_practice.category}." }
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @best_practice.errors, status: :unprocessable_entity }
      end
    end
  end

  protected

  def best_practices_params
    # XXX (cmhobbs) considered harmful but so are stupid rails tricks
    #
    # https://stackoverflow.com/questions/15919761/nested-attributes-unpermitted-parameters/17267343#17267343
    params.permit!
    # BestPractice
    #   .permitted(params)
    #   .merge(Organization.permitted(params))
    #   .merge(params.permit(:best_practice_category_id, :organization_id, :id))
  end
end

app/views/best_practices/_edit_form.html.erb
<%= stylesheet_link_tag "application/best_practice", :media => "all" %>
<%#= javascript_include_tag "application/best_practice" %>
<%= form_for(@best_practice) do |f| %>
  <%# FIXME (cmhobbs) this doesn't belong in the view %>
  <% if @best_practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@best_practice.errors.count, "error") %> prohibited this Idea from being saved:</h2>

      <ul>
        <% @best_practice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span7">


    <%#= hidden_field :organization_id, :value => @best_practice.organization_id %>
    <!--
    <div class="field">
      <%#= f.label :title, "Type *" %>
      <%#= f.select :title, options_for_select(["Key Insight", "Question"], @best_practice.title), include_blank: true, :required => true %>
    </div>
    -->

    <div class="field">
      <%= f.label :title, "Title *" %>
      <%= f.text_field :title, :required => true %>
    </div>

    <div class="field" style="width:90%;">
      <%= f.label "Describe your Key Insight or Question *" %><p class="tabbertab-lbreak"></p>
      <%= f.text_area :body, :cols => 30, :rows => 5, :required => true %>
    </div>

    <div class="field">
      <label>External Link Title (optional)</label>
      <%= f.text_field :link_title %>
    </div>

    <div class="field">
      <%= f.label 'External Link (optional)' %>
      <%= f.text_field :ext_link %>
    </div>


    <br>
    <%= f.check_box :anonymous, { :style => "display:inline;" } %>
    <%= f.label 'Post Anonymously' , { :style => "display:inline;" } %>

    <div class="actions" style="padding-top:20px;">
      <%= f.submit "Edit Insight", :class => 'btn btn-large btn-primary roundedge' %>
    </div>
    <br/ >
    <b>* Required</b>

    <%#= f.hidden_field :organization_id, :value => @organization_id %>
    <%= f.hidden_field :is_public, :value => false %>

  </div>
<% end %>

app/views/best_practices/_form.html.erb
<%= stylesheet_link_tag "application/best_practice", :media => "all" %>
<%#= javascript_include_tag "application/best_practice" %>
<%= form_for(@best_practice, html: { multipart: true }) do |f| %>
  <%# FIXME (cmhobbs) this doesn't belong in the view %>
  <% if @best_practice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@best_practice.errors.count, "error") %> prohibited this Idea from being saved:</h2>

      <ul>
        <% @best_practice.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="span7">
    <% unless defined? group %>
      <div class="row" style="margin: 0;">
        <div class="control-group">
          <div class="controls">
            <%= label_tag "Group * (Hold Command on Mac, or Control on PC, to select multiple groups." %>
            <%= select_tag 'best_practice[organization_id]', options_for_select(all_groups_sorted.collect { |group| [group.title, group.id] }, selected: all_groups_sorted[0]&.id), include_blank: false, :multiple => true, :size => 5, :class => "required", :style => "width: 100%" %>
            <span class="help-inline">This field is required</span>
          </div>
        </div>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :title, "Title *" %>
      <%= f.text_field :title, :required => true %>
    </div>
    <!--
    <div class="field">
      <%#= f.label :title, "Type *" %>
      <%#= f.select :title, options_for_select(["Key Insight", "Question"]), include_blank: true, :required => true %>
    </div>
    <%# unless defined? category %>
      <div class="row">
        <label class="span2">
          <div class="control-group">
            <div class="controls">
              <%#= label_tag "Category *" %>
              <%#= select_tag 'best_practice[best_practice_category_id]', options_for_select(BestPracticeCategory.is_public.sort_by{ |bp| [bp.title]}.collect{ |bp| [bp.title,bp.id]}), include_blank: true, :class => "required" %>
              <span class="help-inline">This field is required</span>
            </div>
          </div>
        </label>
      </div>
    <%# end %>
    -->
    <!--
    <div class="field" style="width:90%;">
      <%#= f.label "Title *" %>
      <p class="tabbertab-lbreak"></p>
      <%#= f.text_field :title, :required => true %>
      <span class="help-inline">This field is required</span>
      <%# if defined? category %>
        <%#= f.hidden_field :best_practice_category_id, :value => best_practice_category_id %>
        <%#= f.hidden_field :category, :value => category %>
        <%#= f.hidden_field :organization_id, :value => organization_id %>
      <%# end %>
    </div>
    -->
    <div class="field" style="width:90%;">
      <%= f.label "Describe your Key Insight or Question *" %><p class="tabbertab-lbreak"></p>
      <%= f.text_area :body, :cols => 30, :rows => 5, :required => true %>
    </div>
    <!--
    <div class="field" style="">
      <%#= f.label "Describe how have you applied it *" %><p class="tabbertab-lbreak"></p>
      <%#= f.text_area :idea_help, :cols => 30, :rows => 5, :required => true %>
    </div>
    -->

    <div class="advanced-options"; margin-top: 20px;">

      <div class="field">
        <label>External Link Title</label>
        <%= f.text_field :link_title %>
      </div>

      <div class="field">
        <%= f.label 'External Link' %>
        <%= f.text_field :ext_link %>
      </div>

      <!--
      <div class="field">
        <%= f.label 'Embed Video/Audio Link' %>
        <%= f.text_area :emb_link %>
      </div>
      -->


      <div class="field"><label>Document</label></div>
      <%# TODO get companies imported here and/or upload functionality %>
      <div class="field">
        <%= f.file_field :documents %>
        <%= f.hidden_field :documents_cache %>
      </div>


      <!--
      <div class="field"><label>Audio</label></div>
      <%# TODO get companies imported here and/or upload functionality %>
      <div class="field">
        <%= f.file_field :audio %>
        <%= f.hidden_field :audio_cache %>
      </div>
      -->
    </div>
    <%# end %>
    <br>
    <%= f.check_box :anonymous, { :style => "display:inline;" } %>
    <%= f.label 'Post Anonymously' , { :style => "display:inline;" } %>

    <div class="actions" style="padding-top:20px;">
      <%= f.submit "Post Insight", :class => 'btn btn-large btn-primary roundedge' %>
    </div>
    <br/ >
    <b>* Required</b>

    <%#= f.hidden_field :organization_id, :value => @organization_id %>
    <%= f.hidden_field :is_public, :value => false %>

  </div>
<% end %>

app/views/best_practices/edit.html.erb
<%= stylesheet_link_tag "application/best_practice", :media => "all" %>
<center>
  <h1 class="knockout-title">edit insight</h1>
</center>


<%= render 'edit_form' %>

app/views/best_practices/index.html.erb
<%= stylesheet_link_tag "application/list-post", :media => "all" %>

<div class="filter-group-list">
  <div class="filter-group-head">
    Show content from:
  </div>
  <% current_user.unique_groups.sort_by!{ |g| g.title }.each do |group| %>
    <div class="filter-group-item">
      <%= link_to group.title, best_practices_path(:organization_id => group.id) %>
    </div>
  <% end %>
  <div class="filter-group-item show-all">
    <%= link_to "All Groups", best_practices_path() %>
  </div>
</div>

<% if @best_practices.count < 1 %>
  <div class="no-post-message">Looks like no one in this group has posted a key insight yet.</div>
  <%= link_to "Post a key insight now", new_best_practice_path(), :class => "btn-primary" %>
<% else %>

  <div class="table-head">
    <div class="main-column">
      <div class="title">Title</div>
    </div>
    <div class="user-column">Member</div>
  </div>
  <div class="clear"></div>

  <% @best_practices.sort_by{ |p| p.created_at}.reverse.each do |post| %>
    <% if User.exists?(:id => post.user_id) %>
      <%= link_to best_practice_path(post), :class => "list-post ripple-button" do %>

        <div class="list-main">
          <div class="title"><%= post.title %></div>
          <div class="info">
            <span class="org-title"><%= Organization.find(post.organization_id).title %></span>
            <br/>
            <% if ((Time.now - post.created_at)/3600).floor < 1 && ((Time.now - post.created_at)/60).floor != 1 %>
              Posted <span class="number">
              <%= ((Time.now - post.created_at)/60).floor %>
              </span> minutes ago
            <% elsif ((Time.now - post.created_at)/60).floor == 1 %>
              Posted <span class="number">
              1</span> minute ago
            <% elsif ((Time.now - post.created_at)/3600).floor < 24 && ((Time.now - post.created_at)/3600).floor != 1 %>
              Posted <span class="number">
              <%= ((Time.now - post.created_at)/3600).floor %>
              </span> hours ago
            <% elsif ((Time.now - post.created_at)/3600).floor ==1 %>
              Posted <span class="number">
              1</span> hour ago
            <% else %>
              <span>
              <%= (post.created_at).strftime("%d %b %Y") %>
              </span>
            <% end %>
            <span> • </span>
            <span class="number">
              <%= post.likers(User).count %>
            </span> Likes
            <span> • </span>
            <span class="number">
              <%= post.comments.count %>
            </span> Comments <!-- this should be "Comments" if not on inquiries, otherwise "Answers" -->
          </div>
        </div>

        <div class="post-list-user">
          <div class="user-chip">
            <% if post.anonymous? %>
              <div class="user-image">
                <%= image_tag "/assets/missing-avatar1.png" %>
              </div>
              <div class="user-name">
                Anonymous
              </div>
            <% else %>
              <div class="user-image">
                <%= image_tag User.find(post.user_id).avatar.url %>
              </div>
              <div class="user-name">
                <%= User.find(post.user_id).name %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="clear"></div>
        
      <% end #link to post path %>
    <% end #if user exists %>
  <% end #do for each post %>
<% end #if there are posts here %>

<div class="clear"></div>

app/views/best_practices/new.html.erb
<%= stylesheet_link_tag "application/best_practice", :media => "all" %>
<center class="knockout-headline">Post an Insight</center>


<%= render 'form' %>

app/views/best_practices/show.html.erb
<%= stylesheet_link_tag "application/best_practice", :media => "all" %>
<%= javascript_include_tag "application/best_practice" %>

<div class="board">
  <% if @best_practice.anonymous? %>
    <div class="user-chip" style="cursor:default;" onmouseover = "this.style.backgroundColor = 'transparent'" onmouseout  = "this.style.backgroundColor = 'transparent'">
      <div class="picture">
        <%= image_tag "/assets/missing-avatar1.png" %>
      </div>
      <div class="name">Anonymous</div>
    </div>
  <% else %>
    <%= link_to user_path(@best_practice.user.id), :class => "user-chip" do %>
      <div class="picture">
        <%= image_tag @best_practice.user.avatar.url %>
      </div>
      <div class="name"><%=@best_practice.user.name %></div>
    <% end %>
  <% end %>
  <div class="column small">

    <div class="info">
      <%= Organization.find(@best_practice.organization_id).title %>
      </br>
      <% if @best_practice.category? %>
        <%= @best_practice.category %>
        </br>
      <% end %>
      <% if ((Time.now - @best_practice.created_at)/3600).floor < 1 && ((Time.now - @best_practice.created_at)/60).floor != 1 %>
        Posted <span class="number">
        <%= ((Time.now - @best_practice.created_at)/60).floor %>
        </span> minutes ago
      <% elsif ((Time.now - @best_practice.created_at)/60).floor == 1 %>
        Posted <span class="number">
        1</span> minute ago
      <% elsif ((Time.now - @best_practice.created_at)/3600).floor < 24 && ((Time.now - @best_practice.created_at)/3600).floor != 1 %>
        Posted <span class="number">
        <%= ((Time.now - @best_practice.created_at)/3600).floor %>
        </span> hours ago
      <% elsif ((Time.now - @best_practice.created_at)/3600).floor ==1 %>
        Posted <span class="number">
        1</span> hour ago
      <% else %>
        <span>
        <%= (@best_practice.created_at).strftime("%d %b %Y") %>
        </span>
      <% end %>
      </br>
      <span class="likes">
        <% if @best_practice.likers(User).count == 1 %>
          <span class="primary-color"><%= @best_practice.likers(User).count %></span> Like
        <% else %>
          <span class="primary-color"><%= @best_practice.likers(User).count %></span> Likes
        <% end %>
      </span>
      <span class="likers">
        <% if @best_practice.likers(User).count < 1 %>
          Be the first to like this
        <% else %>
          <% @best_practice.likers(User).each do |user| %>
            <div><%= user.name %></div>
          <% end %>
        <% end %>
      </span>
      </br>
      <% if @best_practice.comments.count == 1 %>
        <span class="primary-color"><%= @best_practice.comments.count %></span> Comment
      <% else %>
        <span class="primary-color"><%= @best_practice.comments.count %></span> Comments
      <% end %>      
    </div>

    <% if current_user == @best_practice.user %>
      <%= link_to 'Edit', edit_best_practice_path(@best_practice) %>
      <!-- <%= link_to 'Delete', @best_practice, :method => :delete, data: { confirm: 'Are you sure?'} %> -->
       | <%= link_to 'Delete', @best_practice, :method => :delete  %>
    <% elsif (GroupAdmin.where(group_id: @best_practice.organization_id, admin_id: current_user.id).exists?)%>
    <!-- <%= link_to 'Delete', @best_practice, :method => :delete, data: { confirm: 'Are you sure?'} %> -->
    |  <%= link_to 'Delete', @best_practice, :method => :delete %>
    <% end %>
    </br>
    <% if current_user.likes?(@best_practice) %>
      You liked this insight.
    <%else%>
      <% unless current_user == @best_practice.user %>
        <%= link_to 'I like this', like_best_practice_path(:best_practice_id => @best_practice.id), :method => :post, :remote => true, :class => "like" %>
        <span class="liked">You liked this insight.</span>
      <% end %>
    <%end%>
  </div>

  <div class="column large">
    <div class="title"><%= @best_practice.title %></div>

    <div class="body"><%= markdown.render(@best_practice.body).html_safe %></div>

    <% if @best_practice.ext_link? %>
    <div class="subhead">External Link: </div>
    <%= link_to @best_practice.external_link_display_text, @best_practice.ext_link %>
    <% end %>

    <% if @best_practice.documents? %>
    <div class="subhead">Document: </div>
    <p>
      <%= link_to @best_practice.documents.path.split("\/").last, @best_practice.documents.url %>
    </p>
    <% end %>
    <!--
    <%# if @best_practice.idea_help? %>
      <div class="body"><%#= markdown.render(@best_practice.idea_help).html_safe %></div>
    <%# end %>
    -->
  </div>

  <div class="clear"></div>
  
</div>

<div class="board">
  <%= render "comments/form" %>
  <%= render "comments/comments" %>
</div>