config/routes.rb
# NOTE: (cmhobbs) if ArgumentError exceptions arise during boot or on
#      loading routes, first assume clashes with a resources block as
#      noted in the rails 3.2->4.0 upgrade document:
#
#      https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#action-pack
Serve2perform::Application.routes.draw do
  resources :mentorship_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'mentorship_circles/join',  to: 'mentorship_circles#join'
  post 'mentorship_circles/leave', to: 'mentorship_circles#leave'

  resources :collaboration_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'collaboration_circles/join',  to: 'collaboration_circles#join'
  post 'collaboration_circles/leave', to: 'collaboration_circles#leave'

  mount Serve2perform::API => '/'

  resources :inquiries do
    resources :comments
    member do
      get 'documents'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :user_groups do
    collection do
      get ':id/approve' => 'user_groups#approve'
      get 'register'
      get 'manage'
      put 'destroy_many'
      post 'destroy_many'
    end
  end

  resources :coach_action_plans

  resources :mentor_action_plans

  resources :volunteer_action_plans

  resources :comments

  resources :recognitions do
    collection do
      get 'find'
    end
  end

  resources :feedbacks

  resources :facilities do
    collection do
      get 'new'
      get 'show'
      post 'edit'
    end
  end

  resources :testimonials do
    collection do
      get ':id/approve' => 'testimonials#approve'
    end
  end

  resources :fast_contents do
    member do
      get 'documents'
      get 'audio'
    end
  end

  resources :user_licenses do
    collection do
      get 'manage'
      put 'update_many'
    end
  end

  resources :videos

  resources :pacs do
    resources :comments
    collection do
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'cancel'
    end
  end

  resources :pac_members do
    collection do
      get ':id/approve' => 'pac_members#approve'
      get 'register'
      post :invite
    end
  end

  resources :best_practices do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :recommendations do
    resources :comments
    collection do
      get 'find'
      get 'list'
      get ':id/approve' => 'recommendations#approve'
      get 'register_pde'
    end
    member do
      post 'validate', to: 'socializations#validate'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  resources :users do
    collection do
      get 'find'
      get 'historical_opportunities'
      get 'chatter'
      get 'manage'
      put 'update_many'
    end
    member do
      get 'avatars'
    end
  end

  devise_scope :users do
    get '/users/historical_opportunities' => 'users#historical_opportunities'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'

    # FIXME: (cmhobbs) changing this "match" to "get" breaks hard:
    #       Invalid route name, already in use: 'user'
    #
    #       userdefs at line 152 may be messing with it and i'm not
    #       sure if this line is needed anymore?
    # match '/users/:id' => 'users#show', :as => :user
  end

  resources :opportunities do
    collection do
      get :autocomplete_opportunity_title
      post 'update_many'
      get 'edit_many'
      get 'getFacilities'
      get 'getAddress'
      get 'getPrice'
      get 'register_pde'
      get 'getType'
      get 'oneClickRegister'
      get 'oneClickWebRegister'
    end
  end

  resources :competencies, only: [:update]

  resources :assessments

  resources :assessment_reports do
    member do
      get :share
      post :share_with_email
    end
  end

  resources :organizations, param: :slug, only: %i[new create show edit update] do
    member do
      get :sync
      get :sync_linkedin
      get 'findUsers' => 'organizations#find_users'
      get 'analytics' => 'organizations#analytics'
      get 'avatars'
      get 'banners'
      get 'search'
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'resources'
      post 'add_users'
    end
  end

  post 'organizations/leave', to: 'organizations#leave'

  resources :invites do
    collection do
      get :invite_email
      post :send_email
    end
  end

  resources :coupon_uses, only: %i[new create]

  resources :assessment_purchases, only: %i[show new create]

  resources :user_license_purchases, only: %i[show new create]

  resources :single_user_license_purchases, only: %i[show new create]

  resources :opportunity_applications

  resources :opportunity_scholarships, only: %i[new create]

  resources :opportunity_purchases

  resources :recommendation_applications

  resources :support_requests, only: %i[new create]

  resources :skills do
    collection do
      post 'update_many'
      get 'edit_many'
    end
  end

  resources :organization_reports do
    member do
      get  :share
      post :share_with_email
    end
  end

  resources :admin do
    collection do
      get 'reports'
      get 'scholarship_request'
    end
  end

  resources :availability do
    collection do
      post 'edit'
    end
  end

  resources :pac_availability do
    collection do
      post 'edit'
    end
  end

  resources :canvas do
    collection do
      get 'canvas' => 'canvas#index'
      post 'canvas' => 'canvas#post'
      get 'callback' => 'static#callback'
    end
  end

  devise_scope :user do
    # root to: 'home#index'
    root to: 'devise/sessions#new'
  end

  get '/signup' => 'signup#index'

  get '/resources' => 'pages#resources'
  get '/ondemand' => 'pages#on_demand'
  get '/collisions' => 'pages#collisions'
  get '/certifications' => 'pages#certifications'
  get '/about' => 'pages#about'
  get '/speakerseries' => 'pages#speaker_series'
  get '/list' => 'pages#list'
  get '/thoughtleadership' => 'pages#thought_leadership'
  get '/templates' => 'pages#templates'
  get '/marketplace' => 'home#index'

  require 'sidekiq/web'
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'sidekiqadmin' && password == 'S2Pworkers!'
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  require 'resque/server'
  Resque::Server.use(Rack::Auth::Basic) do |username, password|
    username == 'resqueadmin' && password == 'S2Pworkers!'
  end
  mount Resque::Server.new, at: '/resque'

  get '/marketplace/', to: 'marketplace#index'

  post 'accounts/generate', to: 'accounts#generate'
end

app/models/user_group.rb
# == Schema Information
#
# Table name: user_groups
#
#  id        :integer          not null, primary key
#  group_id  :integer
#  member_id :integer
#  approved  :boolean          default(FALSE)
#

class UserGroup < ActiveRecord::Base
  def self.attribute_whitelist
    [:group_id, :member_id, :approved]
  end

  def self.permitted(params)
    params.permit(user_group: self.attribute_whitelist)
  end
  
  belongs_to :group, :class_name => "Organization", :foreign_key => 'group_id'
  belongs_to :member, :class_name => "User", :foreign_key => 'member_id'
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_filter :authenticate_user!

  def register
    @user_group = UserGroup.new({:group_id => user_groups_params[:organization_id], :member_id => current_user.id})
    if @user_group.save
      Notifier.user_group_membership_request(@user_group).deliver_now!
      redirect_to skills_path, :notice => "Thanks for registering! The admin has been emailed."
    else
      redirect_to skills_path, :flash => {:error => @user_group.errors.messages.values.join }
    end
  end

  def manage
    @org = current_user.organization
    @users = @org.members.each_slice(4).to_a
    @mobileusers = @org.members.each_slice(2).to_a
  end

  def destroy_many
    UserGroup.destroy(user_groups_params[:user_groups])

    respond_to do |format|
      format.html { redirect_to manage_user_groups_path, notice: "Members updated" }
    end
  end

  def destroy
    @user_group = UserGroup.find(user_groups_params[:id])
    @user_group.destroy

    respond_to do |format|
      format.html { redirect_to organization_path(current_user.organization.slug), notice: "Member was sucessfully removed." }
      format.json { head :no_content }
    end
  end

  def approve
    @user_group = UserGroup.find(user_groups_params[:id])
    @user_group_org = @user_group.group
    @user_group_admin = @user_group_org.users.where(:role => 'admin')
  end

  def update
    @user_group = UserGroup.find(user_groups_params[:id])
    @user_group.update_attributes(approved: true)
    Notifier.user_group_membership_approval(@user_group).deliver_now!
    redirect_to skills_path, :notice => "Successfully Approved Membership"
  end

  protected

  def user_groups_params
    UserGroup
      .permitted(params)
      .merge(params.permit(user_groups: UserGroup.attribute_whitelist))
      .merge(params.permit(:id, :organization_id))
  end

end

app/views/user_groups/_user_group_approve.html.erb
<%= simple_form_for(@pac_member) do |f| %>

<h1 style="color:#5CCE8B; text-align:center; margin-bottom:20; margin-top:0;">Hello <%= pac_member.member.name %></h1>

<h5 style="text-align: center;">You've been invited to join the <%= pac_member.pac.title %> Collaboration team. Below are the details of the team.</h5>

<div class="pac wrap row">
  <div class="topper">
    <div class="span12">  
      <div class="row">
      
        <%if pac_member.pac.owner_id == current_user.id %>
          <div class="span2 next">
            <%= link_to edit_pac_path do %>
              edit team
            <%end%>
          </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="span12">
    <div class="row">
      <div class="span11">
        <div class="title">
          <%if pac_member.pac.organization.present? %>
            <h4>
              
                <%= pac_member.pac.organization.title %>
             
            </h4>
          <%end%>
          <h2><%= pac_member.pac.title %></h2>
        </div>
      </div>
    </div>

        <div class="row">
            <div class="span2">
              <%if pac_member.pac.start_date? %>
                <div class="start-date">
                  <h6>Start Date</h6>
                  <p><%= pac_member.pac.start_date.strftime("%m/%d/%Y") %></p>
                </div>
              <%end%>
              <%if pac_member.pac.deadline_date? %>
                <div class="deadline-date">
                  <h6>Registration dead line</h6>
                  <p><%= pac_member.pac.deadline_date.strftime("%m/%d/%Y") %></p>
                </div>
              <%end%>
              <%if pac_member.pac.start_time? %>
                <div class="start-time">
                  <h6>Start Time</h6>
                  <p><%= pac_member.pac.start_time %></p>
                </div>
              <%end%>
              <%if pac_member.pac.end_time? %>
                <div class="end-time">
                  <h6>End Time</h6>
                  <p><%= pac_member.pac.end_time %></p>
                </div>
              <%end%>
              <%if pac_member.pac.opportunity_type.blank? || pac_member.pac.opportunity_type.id == 1 %>
                <%if pac_member.pac.location.present? %>
                  <div class="location">
                    <h6>Location</h6>
                    <p><%= pac_member.pac.location %></p>
                  </div>
                <%end%>
              <%end%>
              
              <%if pac_member.pac.facility_id? && pac_member.pac.facility_id != -1 %>
                <div class="facility">
                  <h6>Facility</h6>
                  <p><%= pac_member.pac.facility.name %>
                  <div id="opportunities__facility_address"><%= pac_member.pac.facility.address %></div></p>
                </div>
                <%elsif pac_member.pac.opportunity_type_id.present? %>
                  <div class="location">
                    <h6>Location</h6>
                    <p><%= pac_member.pac.opportunity_type.name %></p>
                  </div>
              <%end%>
              <div class="date">
                <h6>Posted On</h6>
                <p><%= pac_member.pac.created_at.strftime("%B %-d, %Y") %></p>
              </div>

              <% if pac_member.pac.owner_id.present? %>
                <div class="poster">
                  <h6>Posted By</h6>
                  <p><%= link_to pac_member.pac.owner.name, user_path(pac_member.pac.owner.id) %></p>
                </div>
              <% end %>
              
            </div>

          <div class="span9">
            <h4 class="about-vsa">About team
              <% if pac_member.pac.organization.present? && pac_member.pac.organization.website.present? %>
                <%= link_to pac_member.pac.organization.company_website, pac_member.pac.organization.company_website, :target =>"_blank" %>
              <%end%>
            </h4>

            <pre><%= pac_member.pac.description %></pre>

        		<%if pac_member.pac.learning_objectives? %>
          		<h4>TEAM OBJECTIVES</h4>
          		<div class="objtectives">
          			<p><%= pac_member.pac.learning_objectives %></p>
          		</div>        
            <%end%>

            <br/><h4>TEAM MEMBERS</h4>
            <% unless pac_member.pac.pac_members.empty? %>  
              <div>
                <% pac_member.pac.pac_members.each do |pm| %>
                <p><%= pm.member.name %> | <%= mail_to pm.member.email %></p>
              <% end %>
              </div>
              
             <% end %>
          </div>
      </div>
  </div>

</div>


 <div id="approve_recommendation">
 <%= f.button :submit, 'Approve', :class => 'btn btn-large btn-primary' %>
</div>

<%end%>

app/views/user_groups/_user_group_owner_approve.html.erb
<%= simple_form_for(@user_group) do |f| %>

<h1 style="color:#2c9a47; text-align:center; margin-bottom:20; margin-top:0;">Hello <%= current_user.name %></h1>

<h5 style="color:#2c9a47; text-align: center;"><%= link_to user_group.member.name, user_path(user_group.member.id) %> would like to join the <%= user_group.group.title %> User Group.</h5>

 <div style="text-align:center; font-size: 18px; margin-top:20px;">Click Approve to allow <%= user_group.member.name %> into the user group.</div>

 <div id="approve_recommendation">
  <%= f.button :submit, 'Approve', :class => 'btn btn-large btn-primary' %>
 </div>

<%end%>

app/views/user_groups/approve.html.erb
<% if @user_group_admin.map{|usr| usr.id}.include?(current_user.id) %>
  <%= render 'user_group_owner_approve', :user_group => @user_group %>
<% elsif current_user == @user_group.member %>
  <%= render 'user_group_approve', :user_group => @user_group %>
<% end %>

app/views/user_groups/manage.html.erb
<h1>Manage <%= @org.title%>'s Members</h1>
<p>Check the box next to the user's name and click the update button to remove them from the group.</p>

<%= form_tag destroy_many_user_groups_path, :method => :destroy_many do %>		
			<div>
				<table>
				  <tbody>
				    <% @users.each do |row| %>
				      <tr>
				        <% row.each do |column| %>
                         <% column.user_groups.each do |ug| %>
				          <td>
				          	<div>
				             <%= check_box_tag "user_groups[]", ug.id %> <%= column.name %>
				            </div>
				          </td>
				         <% end %>
				        <% end %>
				      </tr>
				    <% end %>
				  </tbody>
				</table>
			</div>
		<%= submit_tag "Update Members", :class => "btn btn-large btn-primary", :style => "margin-top:20px;" %>
<% end %> 