config/routes.rb
# NOTE: (cmhobbs) if ArgumentError exceptions arise during boot or on
#      loading routes, first assume clashes with a resources block as
#      noted in the rails 3.2->4.0 upgrade document:
#
#      https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#action-pack
Serve2perform::Application.routes.draw do
  resources :mentorship_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'mentorship_circles/join',  to: 'mentorship_circles#join'
  post 'mentorship_circles/leave', to: 'mentorship_circles#leave'

  resources :collaboration_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'collaboration_circles/join',  to: 'collaboration_circles#join'
  post 'collaboration_circles/leave', to: 'collaboration_circles#leave'

  mount Serve2perform::API => '/'

  resources :inquiries do
    resources :comments
    member do
      get 'documents'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :user_groups do
    collection do
      get ':id/approve' => 'user_groups#approve'
      get 'register'
      get 'manage'
      put 'destroy_many'
      post 'destroy_many'
    end
  end

  resources :coach_action_plans

  resources :mentor_action_plans

  resources :volunteer_action_plans

  resources :comments

  resources :recognitions do
    collection do
      get 'find'
    end
  end

  resources :feedbacks

  resources :facilities do
    collection do
      get 'new'
      get 'show'
      post 'edit'
    end
  end

  resources :testimonials do
    collection do
      get ':id/approve' => 'testimonials#approve'
    end
  end

  resources :fast_contents do
    member do
      get 'documents'
      get 'audio'
    end
  end

  resources :user_licenses do
    collection do
      get 'manage'
      put 'update_many'
    end
  end

  resources :videos

  resources :pacs do
    resources :comments
    collection do
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'cancel'
    end
  end

  resources :pac_members do
    collection do
      get ':id/approve' => 'pac_members#approve'
      get 'register'
      post :invite
    end
  end

  resources :best_practices do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :recommendations do
    resources :comments
    collection do
      get 'find'
      get 'list'
      get ':id/approve' => 'recommendations#approve'
      get 'register_pde'
    end
    member do
      post 'validate', to: 'socializations#validate'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  resources :users do
    collection do
      get 'find'
      get 'historical_opportunities'
      get 'chatter'
      get 'manage'
      put 'update_many'
    end
    member do
      get 'avatars'
    end
  end

  devise_scope :users do
    get '/users/historical_opportunities' => 'users#historical_opportunities'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'

    # FIXME: (cmhobbs) changing this "match" to "get" breaks hard:
    #       Invalid route name, already in use: 'user'
    #
    #       userdefs at line 152 may be messing with it and i'm not
    #       sure if this line is needed anymore?
    # match '/users/:id' => 'users#show', :as => :user
  end

  resources :opportunities do
    collection do
      get :autocomplete_opportunity_title
      post 'update_many'
      get 'edit_many'
      get 'getFacilities'
      get 'getAddress'
      get 'getPrice'
      get 'register_pde'
      get 'getType'
      get 'oneClickRegister'
      get 'oneClickWebRegister'
    end
  end

  resources :competencies, only: [:update]

  resources :assessments

  resources :assessment_reports do
    member do
      get :share
      post :share_with_email
    end
  end

  resources :organizations, param: :slug, only: %i[new create show edit update] do
    member do
      get :sync
      get :sync_linkedin
      get 'findUsers' => 'organizations#find_users'
      get 'analytics' => 'organizations#analytics'
      get 'avatars'
      get 'banners'
      get 'search'
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'resources'
      post 'add_users'
    end
  end

  post 'organizations/leave', to: 'organizations#leave'

  resources :invites do
    collection do
      get :invite_email
      post :send_email
    end
  end

  resources :coupon_uses, only: %i[new create]

  resources :assessment_purchases, only: %i[show new create]

  resources :user_license_purchases, only: %i[show new create]

  resources :single_user_license_purchases, only: %i[show new create]

  resources :opportunity_applications

  resources :opportunity_scholarships, only: %i[new create]

  resources :opportunity_purchases

  resources :recommendation_applications

  resources :support_requests, only: %i[new create]

  resources :skills do
    collection do
      post 'update_many'
      get 'edit_many'
    end
  end

  resources :organization_reports do
    member do
      get  :share
      post :share_with_email
    end
  end

  resources :admin do
    collection do
      get 'reports'
      get 'scholarship_request'
    end
  end

  resources :availability do
    collection do
      post 'edit'
    end
  end

  resources :pac_availability do
    collection do
      post 'edit'
    end
  end

  resources :canvas do
    collection do
      get 'canvas' => 'canvas#index'
      post 'canvas' => 'canvas#post'
      get 'callback' => 'static#callback'
    end
  end

  devise_scope :user do
    # root to: 'home#index'
    root to: 'devise/sessions#new'
  end

  get '/signup' => 'signup#index'

  get '/resources' => 'pages#resources'
  get '/ondemand' => 'pages#on_demand'
  get '/collisions' => 'pages#collisions'
  get '/certifications' => 'pages#certifications'
  get '/about' => 'pages#about'
  get '/speakerseries' => 'pages#speaker_series'
  get '/list' => 'pages#list'
  get '/thoughtleadership' => 'pages#thought_leadership'
  get '/templates' => 'pages#templates'
  get '/marketplace' => 'home#index'

  require 'sidekiq/web'
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'sidekiqadmin' && password == 'S2Pworkers!'
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  require 'resque/server'
  Resque::Server.use(Rack::Auth::Basic) do |username, password|
    username == 'resqueadmin' && password == 'S2Pworkers!'
  end
  mount Resque::Server.new, at: '/resque'

  get '/marketplace/', to: 'marketplace#index'

  post 'accounts/generate', to: 'accounts#generate'
end

app/controllers/pacs_controller.rb
# FIXME: (cmhobbs) this is unnecessary.  rails should grab lib/points.rb automagically.
require 'points'
include Points

class PacsController < ApplicationController
  before_filter :authenticate_user!

  expose(:all_groups_sorted) do
    current_user.unique_groups.sort_by { |organization| organization.title }
  end

  def index
    if pac_params[:organization_id].present?
      @organization = pac_params[:organization_id] unless pac_params[:organization_id] == ['']
    else
      @organization = current_user.unique_groups
    end

    @pacs = Pac.where(organization_id: @organization)
  end

  def new
    if current_user.active_license == true
      if @pac.nil? && current_pac.empty?

        @pac = Pac.new
        @pacpage = true
        @opportunity_type = OpportunityType.order('id')
        @best_practice_category_id = pac_params[:category_id]
        unless @best_practice_category_id.nil?
          @best_practice_category = BestPracticeCategory.find(@best_practice_category_id)
        end

        respond_to do |format|
          format.html # new.html.erb
          format.json { render json: @pac }
        end
      else
        respond_to do |format|
          format.html { redirect_to find_users_path, notice: 'There is a collaboration team currently in progress.' }
          format.json { render json: @pac }
        end
      end
    else
      respond_to do |format|
        format.html do
          redirect_to new_single_user_license_purchase_path,
                      notice: 'You need an active license to access this feature.'
        end
      end
    end
  end

  def create
    pac = Array(pac_params.fetch(:pacs)).first

    # XXX (cmhobs) what is this doing?  why are the strings 'id' and
    #     'ghost' relevant?
    @pac = Pac.new(pac.reject { |k, _| %w[id ghost].include?(k) })

    @pac.in_progress     = true
    @pac.approval_code   = Array.new(6) { rand(36).to_s(36) }.join
    @pac.organization_id = current_user.organization_id

    @pac[:best_practice_category_id] = (pac_params[:pac][:best_practice_category_id]).to_i

    # XXX (cmhobbs) why are we checking static ids here?  don't do this.
    @pac.approval_status = true if @pac.opportunity_type_id == 5

    if @pac.got_point == false
      Points.give_them_an_collaborator_point(@pac.owner)
      @pac.update_attributes(got_point: true)
    end

    respond_to do |format|
      if @pac.save
        format.html { redirect_to find_users_path, notice: 'Collaboration team was successfully created.' }
        format.json { render json: @pac, status: :created, location: @pac }
      else
        format.html { render action: 'new' }
        format.json { render json: @pac.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @pac              = Pac.find(pac_params[:id])
    @pacpage          = true
    @opportunity_type = OpportunityType.order('id')
    @users            = @pac.pac_members.each_slice(4).to_a
    @mobileusers      = @pac.pac_members.each_slice(2).to_a
    @cancel_pac       = current_pac
  end

  # XXX (cmhobbs) params used as flow control, deeply nested branching
  #     logic, multiple objects being updated that are not the focus
  #     of the controller.  this is the stuff of nightmares.
  def update
    if pac_params[:commit] == 'Verify'
      pac = pac_params.fetch(:pac)
      @pac = Pac.where(
        approval_code: pac[:approval_code],
        id: pac_params.fetch(:id)
      ).first
      if @pac.nil?
        redirect_to pac_availability_path(pac_params.fetch(:id)), flash: { error: 'Please enter a valid code' }
      else
        redirect_to edit_pac_availability_path, notice: 'Your code is correct'
      end
    elsif pac_params[:commit] == 'Confirm'
      pac = pac_params.fetch(:pac)
      @pac = Pac.find(pac_params.fetch(:id))
      @pac.update_attributes(webcast_id: pac[:webcast_id])
      @pac.update_attributes(webcast_facilitator_id: pac[:webcast_facilitator_id])
      if @pac.update_attributes!({ approval_status: true })
        # FIXME: (cmhobbs) change this to asynch delivery
        Notifier.confirm_pac_availability(@pac).deliver_now!
        if @pac.got_point == false
          Points.give_them_an_collaborator_point(@pac.owner)
          @pac.update_attributes(got_point: true)
        end
        @pac.pac_members.each do |member|
          # FIXME: (cmhobbs) change this to asynch delivery
          Notifier.new_pac_email(member, @pac).deliver_now!
        end
        redirect_to root_url, notice: 'Successfully approved collaboration team request'
      else
        redirect_to pac_availability_path,
                    flash: { error: 'There was an error approving your collaboration team request' }
      end
    elsif pac_params[:commit] == 'Reject'
      @pac = Pac.find(pac_params.fetch(:id))
      if @pac.update_attributes!({ approval_status: false })
        # FIXME: (cmhobbs) change this to asynch delivery
        Notifier.reject_pac_availability(@pac).deliver_now!
        redirect_to root_url, notice: 'Successfully rejected the collaboration team request'
      else
        redirect_to pac_availability_path,
                    flash: { error: 'There was an error rejecting your collaboration team request' }
      end
    else

      pac = Array(pac_params.fetch(:pacs)).first
      @pac = Pac.find(pac.fetch(:id))
      @pac.update_attributes(in_progress: nil)
      @pac.update_attributes(complete: true)
      if pac[:is_public].present?
        @pac.update_attributes(is_public: true)
      else
        @pac.update_attributes(is_public: false)
      end
      if @pac.facility.blank? || @pac.facility.approval_name.blank? || @pac.facility.approval_mail.blank?
        @pac.approval_status = true
        @pac.pac_members.each do |member|
          # FIXME: (cmhobbs) change this to asynch delivery
          Notifier.new_pac_email(member, @pac).deliver_now!
        end
      end
      @oppotunity_categories = OpportunityCategory.order('name')
      if @pac.update_attributes(pac.reject { |k, _| %w[id ghost].include?(k) })
        redirect_to pac_path(@pac.id), notice: 'Successfully updated collaboration team'
      else
        render 'edit'
      end
    end
  end

  def show
    @pac         = Pac.find(pac_params[:id])
    @pac_show    = Pac.where(in_progress: 'true')
    @pacpage     = true
    @commentable = @pac
    @comments    = @commentable.comments
    @comment     = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pac }
    end
  end

  def getFacilities
    pac   = Array(pac_params.fetch(:pacs)).first
    state = pac.fetch(:state)
    city  = pac.fetch(:city)

    @data_for_facility = if city == ''
                           Facility.where(state: state).all
                         else
                           Facility.where(state: state, city: city).all
                         end

    render json: @data_for_facility.map { |c| [c.id, c.name] }
  end

  def getAddress
    @data_for_facility = Facility.where(id: pac_params.fetch(:facility_name_dropdown))
    render json: @data_for_facility.map { |c|
                   [c.id, c.address, c.map_location, c.city, c.approval_name, c.approval_mail]
                 }
  end

  def getType
    @data_for_type = OpportunityType.all
    render json: @data_for_type.map { |c| [c.id, c.name] }
  end

  def cancel
    pac = Pac.find(pac_params[:id])
    pac.destroy

    redirect_to find_users_path, notice: 'Collaboration team was successfully canceled.'
  end

  def destroy
    pac = Pac.find(pac_params[:id])
    pac.destroy

    redirect_to user_path(current_user), notice: 'Collaboration team was successfully canceled.'
  end

  protected

  def pac_params
    Pac
      .permitted(params)
      .merge(Facility.permitted(pac_params))
      .merge(params.permit(pacs: Pac.attribute_whitelist))
      .merge(params.permit(
               :approval_code,
               :category_id,
               :city,
               :commit,
               :facility_name_dropdown,
               :id,
               :is_public,
               :organization_id,
               :state,
               :webcast_facilitator_id,
               :webcast_id
             ))
  end
end

app/views/pacs/_auto_complete_user_name.html.erb
<%# FIXME (cmhobbs) relocate this %>
<script>
  $(document).on('ready', function(){
    var availableUsers = <%= Hash[User.all.map {|o| [o.name.downcase, o.id] }].to_json.html_safe %>;
    var availableTags = <%= User.select("name").uniq.map(&:name).to_json.html_safe %>;
    
    $(".auto_complete_user_name").autocomplete({
      source: availableTags
    }).on('blur', function(e) {
      var name = $(e.target).val().toLowerCase();
      var id = availableUsers[name];
      alert(name + "|" + id);
    })
  });
</script>

app/views/pacs/_form.html.erb
<%= stylesheet_link_tag "application/pac", :media => "all" %>
<%= simple_form_for(@pac) do |f| %>
  <% if @pac.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pac.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @pac.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% end %>

app/views/pacs/_newform.html.erb
<%= stylesheet_link_tag "application/pac", :media => "all" %>
<% unless defined? group %>
  <div class="row">
    <label class="span2">
      <div class="control-group">
        <div class="controls">
          <%= label_tag "Group *" %>                           
          <%= select_tag 'best_practice[organization_id]', options_for_select(all_groups_sorted.collect { |group| [group.title, group.id] }), include_blank: true, :class => "required" %>
          <span class="help-inline">This field is required</span>
        </div>
      </div>
    </label>
  </div>
<% end %>

<div class="control-group <%= field_class(pac, :title) %>">
  <%= label_tag "pacs[][title]", "Title of collaboration team", :class => "control-label" %>
  <div class="controls">
    <%= text_field_tag "pacs[][title]", {}, :value => pac.title, :class =>"span7 required string" %>
    <span class="help-inline">This field is required</span>
  </div>
</div>

<div class="control-group <%= field_class(pac, :description) %>">
  <%= label_tag "pacs[][description]", "Description", :class => "control-label"  %>
  <div class="controls">
    <%= text_area_tag "pacs[][description]", pac.description, :class => 'input description span7 required'%>
    <span class="help-inline">This field is required</span>
  </div>
</div>

<h4>Date and Time</h4>
<div class="row">
  <label class="span3">
    <div class="control-group <%= field_class(pac, :start_date) %>">
      <%= label_tag "pacs[][start_date]", "Start Date", :class => "control-label"  %>
      <div class="controls">
        <%= text_field_tag 'pacs[][start_date]', pac.start_date, :placeholder =>"", :class => "span3 required dateTime", maxlength: 5 %>
        <span class="help-inline">This field is required</span>
      </div>
  </div> </label>
  <label class="span2">
    <div class="control-group <%= field_class(pac, :deadline_date) %>">
      <%= label_tag "pacs[][deadline_date]", "Registration deadline", :class => "control-label"  %>
      <div class="controls">
        <%= text_field_tag 'pacs[][deadline_date]', pac.deadline_date, :placeholder =>"", :class => "span3 required dateTime" %>
        <span class="help-inline">This field is required</span>
      </div>
  </div> </label>
</div>
<div class="row">
  <label class="span3">
    <div class="control-group <%= field_class(pac, :start_time) %>">
      <%= label_tag "pacs[][start_time]", "Start Time", :class => "control-label"  %>
      <div class="controls">
        <%= select_tag 'pacs[][start_time]', options_for_select(TimeInterval.times, pac.start_time), :include_blank => true, :placeholder => "", :class =>"span3 required" %>
        <span class="help-inline">This field is required</span>
      </div>
  </div> </label>
  <label class="span2">
    <div class="control-group <%= field_class(pac, :end_time) %>">
      <%= label_tag "pacs[][end_time]", "End Time", :class => "control-label"  %>
      <div class="controls">
        <%= select_tag 'pacs[][end_time]', options_for_select(TimeInterval.times, pac.end_time), :include_blank => true, :placeholder => "", :class =>"span3 required" %>
        <span class="help-inline">This field is required</span>
      </div>
  </div> </label>
</div>
<h4>Number of members</h4>
<div class="row">
  <label class="span3">
    <div class="control-group <%= field_class(pac, :max_students) %>">
      <%= label_tag "pacs[][max_students]", "Max", :class => "control-label"  %>
      <div class="controls">
        <%= text_field_tag 'pacs[][max_students]', pac.max_students, :placeholder =>"", :class => "span3 required", maxlength: 5 %>
        <span class="help-inline">This field is required</span>
      </div>
  </div> </label>
  <label class="span2">
    <div class="control-group <%= field_class(pac, :min_students) %>">
      <%= label_tag "pacs[][min_students]", "Min", :class => "control-label"  %>
      <div class="controls">
        <%= text_field_tag 'pacs[][min_students]', pac.min_students, :placeholder =>"", :class => "span3 required", maxlength: 5 %>
        <span class="help-inline">This field is required</span>
      </div>
  </div> </label>
</div>

<%#= hidden_field_tag 'pacs[][is_public]', pac.is_public, :value => 0 %>

app/views/pacs/_pac.html.erb
<div id="panel" style="display: none;">
	<div class="pac-contents">
		<center>
		  <b>TEAM:</b>
		  <%= pac.title %>
		</center>

		<p>
		  <center><b>team members:</b></center>
		  <table class="pac-table">
		  <%= render(pac.pac_members) %>
		  </table>
		</p>
		<% unless pac.id == nil %>
		<%= link_to "Finalize", edit_pac_path(pac), :class => "btn btn-primary", :style => "margin-bottom:6px;" %>
		<%= link_to "Cancel team", cancel_pacs_path(:id => pac), :class => "btn btn-primary", :style => "margin-bottom:6px;", 
			data: { confirm: 'Are you sure?'} %>
		<% end %>
	</div>	
</div>
<p class="slide"><a href="#" class="btn-slide">Team Panel</a></p>

app/views/pacs/index.html.erb
<%= stylesheet_link_tag "application/list-post", :media => "all" %>

<div class="filter-group-list">
  <div class="filter-group-head">
    Show content from:
  </div>
  <% current_user.unique_groups.each do |group| %>
    <div class="filter-group-item">
      <%= link_to group.title, pacs_path(:organization_id => group.id) %>
    </div>
  <% end %>
  <div class="filter-group-item show-all">
    <%= link_to "All Groups", pacs_path() %>
  </div>
</div>

<% if @pacs.count < 1 %>
  <div class="no-post-message">Looks like no one in this group has posted a collaboration group yet.</div>
  <%= link_to "Post a collaboration group now", new_pac_path(), :class => "btn-primary" %>
<% else %>

  <div class="table-head">
    <div class="main-column">
      <div class="title">Title</div>
    </div>
    <div class="user-column">Posted By</div>
  </div>
  <div class="clear"></div>

  <% @pacs.sort_by{ |p| p.created_at}.reverse.each do |post| %>
    <% if User.exists?(:id => post.owner_id) %>
      <%= link_to pac_path(post), :class => "list-post ripple-button" do %>

        <div class="list-main">
          <div class="title"><%= post.title %></div>
          <div class="info">
            <span class="org-title"><%= Organization.find(post.organization_id).title %><span class="org-title">
            <br/>
            <% if ((Time.now - post.created_at)/3600).floor < 1 && ((Time.now - post.created_at)/60).floor != 1 %>
              Posted <span class="number">
              <%= ((Time.now - post.created_at)/60).floor %>
              </span> minutes ago
            <% elsif ((Time.now - post.created_at)/60).floor == 1 %>
              Posted <span class="number">
              1</span> minute ago
            <% elsif ((Time.now - post.created_at)/3600).floor < 24 && ((Time.now - post.created_at)/3600).floor != 1 %>
              Posted <span class="number">
              <%= ((Time.now - post.created_at)/3600).floor %>
              </span> hours ago
            <% elsif ((Time.now - post.created_at)/3600).floor ==1 %>
              Posted <span class="number">
              1</span> hour ago
            <% else %>
              <span>
              <%= (post.created_at).strftime("%d %b %Y") %>
              </span>
            <% end %>
            <% if post.complete %>
              <span> • </span>
              <span>Complete</span>
            <% else %>
              <span> • </span>
              <span class="number">Open</span>
            <% end %>
          </div>
        </div>

        <div class="post-list-user">
          <div class="user-chip">
            <div class="user-image">
              <%= image_tag User.find(post.owner_id).avatar.url %>
            </div>
            <div class="user-name">
              <%= User.find(post.owner).name %>
            </div>
          </div>
        </div>
        <div class="clear"></div>

      <% end #link to post path %>
    <% end #if user exists %>
  <% end #do for each post %>
<% end #if there are posts here %>

<div class="clear"></div>

app/views/pacs/newold.html.erb
<h1>New Pac</h1>

<%= render 'form' %>

<%= link_to 'Back', pacs_path %>

app/views/pacs/show.html.erb
<%= stylesheet_link_tag "application/pac", :media => "all" %>
<div class="pac wrap row">
  <div class="topper">
    <div class="span12">  
      <div class="row">
      
        <%if @pac.owner_id == current_user.id %>
          <div class="span2 next" style="width:185px;">
            <%= link_to edit_pac_path do %>
              edit collaboration team
            <%end%>
          </div>
        <%end%>
      </div>
    </div>
  </div>
  <div class="span12">
    <div class="row">
      <div class="span11">
        <div class="title">
          <%if @pac.organization.present? %>
            <h4>
              
                <%= @pac.organization.title %>
             
            </h4>
          <%end%>
          <h2><%= @pac.title %></h2>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="span2">
        <%if @pac.organization.present? && @pac.organization.avatar_path.present? %>
          <div class="avatar">
            <%= link_to organization_path(@pac.organization.slug) do %>
              <%= image_tag @pac.organization.avatar.url %>
            <%end%>
          </div>
        <%end%>
        <div style="margin-top:5px;">
          <% if @pac.is_public? %>
            <% unless @pac.owner_id == current_user.id || @pac.pac_members.include?(current_user) %>
                <%= link_to 'Register for team', {:controller => :pac_members, :id => @pac.id, :action => :register}, {:class =>"btn btn-large btn-primary pac roundedge"} %>
            <% end %>
          <% end %>
        </div>
        <%if @pac.start_date? %>
          <div class="start-date">
            <h6>Start Date</h6>
            <p><%= @pac.start_date.strftime("%m/%d/%Y") %></p>
          </div>
        <%end%>
        <%if @pac.deadline_date? %>
          <div class="deadline-date">
            <h6>Registration dead line</h6>
            <p><%= @pac.deadline_date.strftime("%m/%d/%Y") %></p>
          </div>
        <%end%>
        <%if @pac.start_time? %>
          <div class="start-time">
            <h6>Start Time</h6>
            <p><%= @pac.start_time %></p>
          </div>
        <%end%>
        <%if @pac.end_time? %>
          <div class="end-time">
            <h6>End Time</h6>
            <p><%= @pac.end_time %></p>
          </div>
        <%end%>
        <%if @pac.opportunity_type.blank? || @pac.opportunity_type.id == 1 %>
          <%if @pac.location.present? %>
            <div class="location">
              <h6>Location</h6>
              <p><%= @pac.location %></p>
            </div>
          <%end%>
        <%end%>
        
        <%if @pac.facility_id? && @pac.facility_id != -1 %>
          <div class="facility">
            <h6>Facility</h6>
            <p><%= @pac.facility.name %>
            <div id="opportunities__facility_address"><%= @pac.facility.address %></div></p>
          </div>
          <%elsif @pac.opportunity_type_id.present? %>
            <div class="location">
              <h6>Location</h6>
              <p><%= @pac.opportunity_type.name %></p>
            </div>
        <%end%>

        <% if @pac.opportunity_type.id == 2 %>
          <div class="facility">
              <h6>Online information</h6>
              <p>
                <%= markdown.render(@pac.online_info).html_safe %>
              </p>
          </div>
        <% end %>

        <div class="date">
          <h6>Posted On</h6>
          <p><%= @pac.created_at.strftime("%B %-d, %Y") %></p>
        </div>

        <% if @pac.owner_id.present? %>
          <div class="poster">
            <h6>Posted By</h6>
            <p><%= link_to @pac.owner.name, user_path(@pac.owner.id) %></p>
          </div>
        <% end %>


      </div>

      <div class="span9">
        <h4 class="about-vsa">About collaboration team
          <% if @pac.organization.present? && @pac.organization.website.present? %>
            <%= link_to @pac.organization.company_website, @pac.organization.company_website, :target =>"_blank" %>
          <%end%>
        </h4>

        <pre><%= @pac.description %></pre>

        <%if @pac.learning_objectives? %>
          <h4>TEAM OBJECTIVES</h4>
          <div class="objtectives">
            <p><%= @pac.learning_objectives %></p>
          </div>        
        <%end%>

        <br/><h4>TEAM MEMBERS</h4>
        <% unless @pac.pac_members.empty? %>  
          <div>
            <% @pac.pac_members.each do |pm| %>
            <p><%= pm.member.name %> | <%= mail_to pm.member.email %></p>
          <% end %>
          </div>
          
         <% end %>

         <%= render "comments/comments" %>
         <%= render "comments/form" %>

      </div>
    </div>
    
    
  </div>
</div>