config/routes.rb
# NOTE: (cmhobbs) if ArgumentError exceptions arise during boot or on
#      loading routes, first assume clashes with a resources block as
#      noted in the rails 3.2->4.0 upgrade document:
#
#      https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#action-pack
Serve2perform::Application.routes.draw do
  resources :mentorship_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'mentorship_circles/join',  to: 'mentorship_circles#join'
  post 'mentorship_circles/leave', to: 'mentorship_circles#leave'

  resources :collaboration_circles do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  post 'collaboration_circles/join',  to: 'collaboration_circles#join'
  post 'collaboration_circles/leave', to: 'collaboration_circles#leave'

  mount Serve2perform::API => '/'

  resources :inquiries do
    resources :comments
    member do
      get 'documents'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :user_groups do
    collection do
      get ':id/approve' => 'user_groups#approve'
      get 'register'
      get 'manage'
      put 'destroy_many'
      post 'destroy_many'
    end
  end

  resources :coach_action_plans

  resources :mentor_action_plans

  resources :volunteer_action_plans

  resources :comments

  resources :recognitions do
    collection do
      get 'find'
    end
  end

  resources :feedbacks

  resources :facilities do
    collection do
      get 'new'
      get 'show'
      post 'edit'
    end
  end

  resources :testimonials do
    collection do
      get ':id/approve' => 'testimonials#approve'
    end
  end

  resources :fast_contents do
    member do
      get 'documents'
      get 'audio'
    end
  end

  resources :user_licenses do
    collection do
      get 'manage'
      put 'update_many'
    end
  end

  resources :videos

  resources :pacs do
    resources :comments
    collection do
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'cancel'
    end
  end

  resources :pac_members do
    collection do
      get ':id/approve' => 'pac_members#approve'
      get 'register'
      post :invite
    end
  end

  resources :best_practices do
    resources :comments
    member do
      get 'documents'
      get 'audio'
      post 'like', to: 'socializations#like'
      get 'duplicate'
    end
  end

  resources :recommendations do
    resources :comments
    collection do
      get 'find'
      get 'list'
      get ':id/approve' => 'recommendations#approve'
      get 'register_pde'
    end
    member do
      post 'validate', to: 'socializations#validate'
    end
  end

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'registrations',
    sessions: 'sessions'
  }

  resources :users do
    collection do
      get 'find'
      get 'historical_opportunities'
      get 'chatter'
      get 'manage'
      put 'update_many'
    end
    member do
      get 'avatars'
    end
  end

  devise_scope :users do
    get '/users/historical_opportunities' => 'users#historical_opportunities'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'

    # FIXME: (cmhobbs) changing this "match" to "get" breaks hard:
    #       Invalid route name, already in use: 'user'
    #
    #       userdefs at line 152 may be messing with it and i'm not
    #       sure if this line is needed anymore?
    # match '/users/:id' => 'users#show', :as => :user
  end

  resources :opportunities do
    collection do
      get :autocomplete_opportunity_title
      post 'update_many'
      get 'edit_many'
      get 'getFacilities'
      get 'getAddress'
      get 'getPrice'
      get 'register_pde'
      get 'getType'
      get 'oneClickRegister'
      get 'oneClickWebRegister'
    end
  end

  resources :competencies, only: [:update]

  resources :assessments

  resources :assessment_reports do
    member do
      get :share
      post :share_with_email
    end
  end

  resources :organizations, param: :slug, only: %i[new create show edit update] do
    member do
      get :sync
      get :sync_linkedin
      get 'findUsers' => 'organizations#find_users'
      get 'analytics' => 'organizations#analytics'
      get 'avatars'
      get 'banners'
      get 'search'
      get 'getFacilities'
      get 'getAddress'
      get 'getType'
      get 'resources'
      post 'add_users'
    end
  end

  post 'organizations/leave', to: 'organizations#leave'

  resources :invites do
    collection do
      get :invite_email
      post :send_email
    end
  end

  resources :coupon_uses, only: %i[new create]

  resources :assessment_purchases, only: %i[show new create]

  resources :user_license_purchases, only: %i[show new create]

  resources :single_user_license_purchases, only: %i[show new create]

  resources :opportunity_applications

  resources :opportunity_scholarships, only: %i[new create]

  resources :opportunity_purchases

  resources :recommendation_applications

  resources :support_requests, only: %i[new create]

  resources :skills do
    collection do
      post 'update_many'
      get 'edit_many'
    end
  end

  resources :organization_reports do
    member do
      get  :share
      post :share_with_email
    end
  end

  resources :admin do
    collection do
      get 'reports'
      get 'scholarship_request'
    end
  end

  resources :availability do
    collection do
      post 'edit'
    end
  end

  resources :pac_availability do
    collection do
      post 'edit'
    end
  end

  resources :canvas do
    collection do
      get 'canvas' => 'canvas#index'
      post 'canvas' => 'canvas#post'
      get 'callback' => 'static#callback'
    end
  end

  devise_scope :user do
    # root to: 'home#index'
    root to: 'devise/sessions#new'
  end

  get '/signup' => 'signup#index'

  get '/resources' => 'pages#resources'
  get '/ondemand' => 'pages#on_demand'
  get '/collisions' => 'pages#collisions'
  get '/certifications' => 'pages#certifications'
  get '/about' => 'pages#about'
  get '/speakerseries' => 'pages#speaker_series'
  get '/list' => 'pages#list'
  get '/thoughtleadership' => 'pages#thought_leadership'
  get '/templates' => 'pages#templates'
  get '/marketplace' => 'home#index'

  require 'sidekiq/web'
  if Rails.env.production?
    Sidekiq::Web.use Rack::Auth::Basic do |username, password|
      username == 'sidekiqadmin' && password == 'S2Pworkers!'
    end
  end
  mount Sidekiq::Web, at: '/sidekiq'

  require 'resque/server'
  Resque::Server.use(Rack::Auth::Basic) do |username, password|
    username == 'resqueadmin' && password == 'S2Pworkers!'
  end
  mount Resque::Server.new, at: '/resque'

  get '/marketplace/', to: 'marketplace#index'

  post 'accounts/generate', to: 'accounts#generate'
end

app/views/opportunity_purchases/new.html.erb
<% if params[:opportunity_id].present? %>
  <% opportunity_id = params[:opportunity_id] %>
<%elsif params[:recommendation_id].present? %>
  <% recommendation_id = params[:recommendation_id] %>
<% end %>
<%= content_for(:head) do %>
  <%# FIXME (cmhobbs) relocate this %>
  <script type="text/javascript" src="https://js.stripe.com/v1/"></script>
  <script type="text/javascript">
    Stripe.setPublishableKey('<%= PUBLISHABLE_STRIPE_KEY %>');
      $(document).ready(function() {
          function addInputNames() {
              // Not ideal, but jQuery's validate plugin requires fields to have names
              // so we add them at the last possible minute, in case any javascript 
              // exceptions have caused other parts of the script to fail.
              $(".card-number").attr("name", "card-number")
              $(".card-cvc").attr("name", "card-cvc")
              $(".card-expiry-year").attr("name", "card-expiry-year")
          }

          function removeInputNames() {
              $(".card-number").removeAttr("name")
              $(".card-cvc").removeAttr("name")
              $(".card-expiry-year").removeAttr("name")
          }

          function submit(form) {
              // remove the input field names for security
              // we do this *before* anything else which might throw an exception
              removeInputNames(); // THIS IS IMPORTANT!

              // given a valid form, submit the payment details to stripe
              $(form['submit-button']).attr("disabled", "disabled")

              Stripe.createToken({
                  number: $('.card-number').val(),
                  cvc: $('.card-cvc').val(),
                  exp_month: $('.card-expiry-month').val(), 
                  exp_year: $('.card-expiry-year').val()
              }, function(status, response) {
                  if (response.error) {
                      // re-enable the submit button
                      $(form['submit-button']).removeAttr("disabled")
  
                      // show the error
                      $(".payment-errors").html(response.error.message);

                      // we add these names back in so we can revalidate properly
                      addInputNames();
                  } else {
                      // token contains id, last4, and card type
                      var token = response['id'];

                      // insert the stripe token
                      var input = $("<input name='stripeToken' value='" + token + "' style='display:none;' />");
                      form.appendChild(input[0])

                      // and submit
                      form.submit();
                  }
              });
              
              return false;
          }
          
          // add custom rules for credit card validating
          jQuery.validator.addMethod("cardNumber", Stripe.validateCardNumber, "Please enter a valid card number");
          jQuery.validator.addMethod("cardCVC", Stripe.validateCVC, "Please enter a valid security code");
          jQuery.validator.addMethod("cardExpiry", function() {
              return Stripe.validateExpiry($(".card-expiry-month").val(), 
                                           $(".card-expiry-year").val())
          }, "Please enter a valid expiration");

          // We use the jQuery validate plugin to validate required params on submit
          $("#example-form").validate({
              submitHandler: submit,
              rules: {
                  "card-cvc" : {
                      cardCVC: true,
                      required: true
                  },
                  "card-number" : {
                      cardNumber: true,
                      required: true
                  },
                  "card-expiry-year" : "cardExpiry" // we don't validate month separately
              }
          });

          // adding the input field names is the last step, in case an earlier step errors                
          addInputNames();
      });
  </script>
<% end %>
<div class="container">
  <div class="row">
    <div class="span8 center">
      <h4><span><%= image_tag "lockicon_purchase.png", :alt =>'lockicon_purchase' %></span>PerformanceGPA<span>&#0153;</span>  Skill Checkout 
        <span class="exit">
          <%= link_to :back do  %>
            <%= image_tag "exit.png" , :alt =>'exit' %>
          <% end %></span>          
     </h4>

      <%= form_tag opportunity_purchases_path, :id => 'example-form', :style => 'display:none;' do %>
      <% if opportunity_id.present? %>
        <%= hidden_field_tag 'opportunity_id', opportunity_id%>
      <% elsif recommendation_id.present? %>
        <%= hidden_field_tag 'recommendation_id', recommendation_id%>
        <%end%>
        <h4 class="total">Total <span>$25.00</span></h5>
        <h4 class="heading">Credit Card Information</h5>
        <div class="form-row">
            <%= label_tag "name", "Your Name" %>
            <%= text_field_tag 'name', current_user.name, :class => 'input required user_name', :placeholder =>"" %>
        </div>

        <div class="form-row">
            <%= label_tag "email", "Email" %>
            <%= text_field_tag 'email', current_user.email, :class => 'required email', :placeholder =>"" %>
        </div>            

        <div class="form-row">
            <%= label_tag "card-number", "Card Number" %>
            <input type="text" maxlength="16" autocomplete="off" class="card-number stripe-sensitive required card-number" placeholder="" />
        </div>

        <div class="form-row">
            <div class="expiry-wrapper">
                <label class="exp-date">Expiration Month
                  <div class="styled-select">
                    <select class="card-expiry-month stripe-sensitive required">
                    </select>
                  </div>
                  <script type="text/javascript">
                      var select = $(".card-expiry-month"),
                          month = new Date().getMonth() + 1;
                      for (var i = 1; i <= 12; i++) {
                          select.append($("<option value='"+i+"' "+(month === i ? "selected" : "")+">"+i+"</option>"))
                      }
                  </script>
                </label>
                <label class="exp-date">Expiration Year
                  <div class="styled-select">
                    <select class="card-expiry-year stripe-sensitive required">
                    </select>
                  </div>
                </label>
                <script type="text/javascript">
                    var select = $(".card-expiry-year"),
                        year = new Date().getFullYear();

                    for (var i = 0; i < 12; i++) {
                        select.append($("<option value='"+(i + year)+"' "+(i === 0 ? "selected" : "")+">"+(i + year)+"</option>"))
                    }
                </script>

                <label>CVC
                  <input type="text" maxlength="4" autocomplete="off" class="card-cvc stripe-sensitive required" placeholder="" />
                </label>
            </div>
        </div>

        <div class="form-row last">
        <button type="submit" name="submit-button" class="submit_button roundedge">Submit Order</button>
        <div class="cancel button"><%= link_to 'Cancel', :back  %></div>
        </div>
        <span class="payment-errors"></span>
      </div>
    </div>
  </div>
<% end %>


<!-- 
    The easiest way to indicate that the form requires JavaScript is to show
    the form with JavaScript (otherwise it will not render). You can add a
    helpful message in a noscript to indicate that users should enable JS.
-->
<script>if (window.Stripe) $("#example-form").show()</script>
<noscript><p>JavaScript is required for the registration form.</p></noscript>

app/views/opportunity_purchases/show.html.erb
<div class="container">
  <div class="row">
  	<div class="span12">
			<h2 class="page title">Thank you for your order</h2>
			<h4 class="page title-sec">We will send you a confirmation email for your records shortly</h4>
	</div>
  </div>
   <div class="row">
    <div class="span8 center">
      <h4><span><%= image_tag "lockicon_purchase.png" , :alt =>'lockicon_purchase'%>Order confirmation number <%= @opportunity_purchase.id %></h4>

      
      	<h3 class="order-title">Your Order Details</h3>

      	<div class="order-details">
      		<h4><%= "Customer Name:  #{@opportunity_purchase.user.name}" %></h4>
      		<h4><%= "Order Number:  #{@opportunity_purchase.id}" %></h4>
      		<h4><%= "Order Date:  #{@opportunity_purchase.created_at.strftime("%m-%d-%Y")}" %></h4>
      		<h4><%= "Payment Method:  #{@charge_object.card.type}" %></h4>
      		
      		</div>

      		<div class="payment-amount">
      			<h4>Total
      				<span><span class="d">$</span><%= @charge_amount.to_i %><span>.00</span></span>
      			</h4>
      		</div>
      		<div class="begin-assessment">
            <% if @opportunity_purchase.skill_type == "recommendation" %>
            <%= link_to 'Click to Complete Connect', new_recommendation_application_path(:recommendation_id =>@opportunity_purchase.opportunity.id) %>
            <%else %>
      			<%= link_to 'Back to Skills',  skills_path %>
            <%end%>
      		</div>
      	
	</div>
  </div>
</div>